/**:
  ros__parameters:
    frames/odom: dlio_odom
    frames/baselink: base_link
    frames/lidar: front_lidar_link
    frames/imu: imu_link

    extrinsics/baselink2imu/t: [0.34629,  -0.00914,  0.04218]
    extrinsics/baselink2imu/R: [ 0.,  0.,  1.,
                                 1.,  0.,  0.,
                                 0.,  1.,  0. ]
    extrinsics/baselink2lidar/t: [0.33767,  0.000,  0.08134]
    extrinsics/baselink2lidar/R: [ 0.,  0.,  1.,
                                   1.,  0.,  0.,
                                   0.,  1.,  0. ]
